In [4]:
import pandas as pd
df=pd.read_excel("Project_3_Banking_Loan_Analysis.xlsx")

In [5]:
df.head()

,Application_ID,Age,Gender,Employment_Type,Annual_Income,Credit_Score,Loan_Type,Loan_Amount,Loan_Tenure_Years,Existing_Loans,Region,Debt_to_Income_Ratio,Loan_Status
0,APP0001,32,Male,Self-Employed,1214341,826,Home Loan,276454,3,1,West,0.63,Rejected
1,APP0002,44,Female,Salaried,2278911,835,Personal Loan,2230647,15,1,West,0.17,Approved
2,APP0003,45,Male,Salaried,949728,786,Personal Loan,544501,15,0,North,0.13,Approved
3,APP0004,24,Male,Self-Employed,2391471,769,Education Loan,4441862,15,3,South,0.30,Approved
4,APP0005,25,Male,Self-Employed,214307,693,Vehicle Loan,4021088,10,1,West,0.36,Rejected

In [6]:
df.shape

(700, 13)

In [7]:
df.columns

Index(['Application_ID', 'Age', 'Gender', 'Employment_Type', 'Annual_Income',
       'Credit_Score', 'Loan_Type', 'Loan_Amount', 'Loan_Tenure_Years',
       'Existing_Loans', 'Region', 'Debt_to_Income_Ratio', 'Loan_Status'],
      dtype='object')

In [8]:
df.dtypes

Application_ID           object
Age                       int64
Gender                   object
Employment_Type          object
Annual_Income             int64
Credit_Score              int64
Loan_Type                object
Loan_Amount               int64
Loan_Tenure_Years         int64
Existing_Loans            int64
Region                   object
Debt_to_Income_Ratio    float64
Loan_Status              object
dtype: object

In [10]:
df["Annual_Income"].max()

2499697

In [12]:
df["Loan_Type"].unique()

array(['Home Loan', 'Personal Loan', 'Education Loan', 'Vehicle Loan'],
      dtype=object)

In [13]:
df["Loan_Tenure_Years"].max()

20

In [14]:
df["Loan_Tenure_Years"].min()

2

In [16]:
df[df["Loan_Status"]=="Approved"]["Application_ID"].count()

np.int64(244)

In [20]:
df[df["Loan_Status"]=="Approved"].shape[0]

244

In [5]:
import pandas as pd
df=pd.read_excel("Project_3_Banking_Loan_Analysis.xlsx")

In [6]:
df["Loan_Status"].value_counts()

Loan_Status
Rejected    456
Approved    244
Name: count, dtype: int64

In [7]:
df["Loan_Amount"].sum()

np.int64(1758716871)

In [8]:
df["Loan_Amount"].mean()

np.float64(2512452.672857143)

In [9]:
df["Loan_Amount"].max()

4999802

In [10]:
df["Loan_Amount"].min()

51598

In [11]:
df.groupby("Loan_Status")["Loan_Amount"].mean()

Loan_Status
Approved    2.427657e+06
Rejected    2.557826e+06
Name: Loan_Amount, dtype: float64

In [12]:
df.groupby("Loan_Status")["Loan_Amount"].sum()

Loan_Status
Approved     592348195
Rejected    1166368676
Name: Loan_Amount, dtype: int64

In [13]:
df.groupby("Loan_Status")["Credit_Score"].mean()

Loan_Status
Approved    750.549180
Rejected    635.223684
Name: Credit_Score, dtype: float64

In [16]:
(df["Loan_Status"]=="Approved").mean()*100

np.float64(34.85714285714286)

In [17]:
df.groupby("Employment_Type")["Application_ID"].count()

Employment_Type
Business         150
Salaried         388
Self-Employed    162
Name: Application_ID, dtype: int64

In [18]:
df.groupby("Employment_Type")["Annual_Income"].mean()

Employment_Type
Business         1.223281e+06
Salaried         1.337498e+06
Self-Employed    1.298419e+06
Name: Annual_Income, dtype: float64

In [19]:
df[df["Annual_Income"] > 1000000]["Application_ID"].count()

np.int64(439)

In [20]:
df["Credit_Score"].mean()

np.float64(675.4228571428572)

In [1]:
import pandas as pd
df=pd.read_excel("Project_3_Banking_Loan_Analysis.xlsx")

In [8]:
def credit_category(score):
    
     if score < 600: 
         return "Low"
     elif score <=750:
         return "Medium"
     else:
         return "High"

df["Credit_Category"] = df["Credit_Score"].apply(credit_category)

In [9]:
df["Credit_Category"].value_counts()

Credit_Category
Medium    297
Low       204
High      199
Name: count, dtype: int64

In [10]:
df[df["Loan_Status"] == "Approved"].groupby("Credit_Category")["Application_ID"].count()

Credit_Category
High      126
Medium    118
Name: Application_ID, dtype: int64

In [19]:
df.groupby("Credit_Category")["Loan_Status"].apply(lambda x: (x == "Approved").mean() * 100)

Credit_Category
High      63.316583
Low        0.000000
Medium    39.730640
Name: Loan_Status, dtype: float64

In [20]:
df[["Annual_Income", "Loan_Amount"]].corr()

               Annual_Income  Loan_Amount
Annual_Income       1.000000    -0.088725
Loan_Amount        -0.088725     1.000000

In [2]:
import pandas as pd
df=pd.read_excel("Project_3_Banking_Loan_Analysis.xlsx")

In [3]:
df[["Loan_Amount","Credit_Score"]].corr()

              Loan_Amount  Credit_Score
Loan_Amount        1.0000       -0.0216
Credit_Score      -0.0216        1.0000

In [4]:
df["Annual_Income"].max()

2499697

In [6]:
df[df["Annual_Income"] > 1000000]["Loan_Amount"].mean()

np.float64(2433609.054669704)

In [5]:
df["Annual_Income"].min()

180746

In [9]:
def credit_category(score):
    
     if score < 600: 
         return "Low"
     elif score <=750:
         return "Medium"
     else:
         return "High"

df["Credit_Category"] = df["Credit_Score"].apply(credit_category)

In [10]:
df[df["Credit_Category"] == "High"]["Loan_Amount"].mean()

np.float64(2477525.1909547737)

In [12]:
Q1=df["Loan_Amount"].quantile(0.25)
Q3=df["Loan_Amount"].quantile(0.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

print("LOWER:",lower)
print("UPPER:",upper)

LOWER: -2494844.875
UPPER: 7457344.125

In [16]:
outliers= df[(df["Loan_Amount"]<lower)|(df["Loan_Amount"]>upper)]

In [17]:
Q1=df["Annual_Income"].quantile(0.25)
Q3=df["Annual_Income"].quantile(0.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

print("LOWER:",lower)
print("UPPER:",upper)

LOWER: -954597.875
UPPER: 3580953.125

In [19]:
outliers=df[(df["Annual_Income"]<lower)|(df["Annual_Income"]>upper)]

In [20]:
df[["Age", "Annual_Income", "Loan_Amount", "Credit_Score"]].corr()

                    Age  Annual_Income  Loan_Amount  Credit_Score
Age            1.000000       0.030834     0.006554      0.042125
Annual_Income  0.030834       1.000000    -0.088725      0.021745
Loan_Amount    0.006554      -0.088725     1.000000     -0.021600
Credit_Score   0.042125       0.021745    -0.021600      1.000000

In [22]:
df[df["Loan_Status"] == "Approved"].groupby("Employment_Type")["Application_ID"].count()

Employment_Type
Business          50
Salaried         141
Self-Employed     53
Name: Application_ID, dtype: int64

In [25]:
approval_rate = (
    df.groupby("Employment_Type")["Loan_Status"]
      .apply(lambda x: (x == "Approved").mean() * 100))

In [26]:
approval_rate

Employment_Type
Business         33.333333
Salaried         36.340206
Self-Employed    32.716049
Name: Loan_Status, dtype: float64

In [27]:
approval_rate = (
    df.groupby("Credit_Category")["Loan_Status"]
      .apply(lambda x: (x == "Approved").mean() * 100)
)

In [28]:
approval_rate

Credit_Category
High      63.316583
Low        0.000000
Medium    39.730640
Name: Loan_Status, dtype: float64